services:
  - type: web
    name: soakoja-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: APP_PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true
    branch: main